version: '3.1'

services:
  poller:
    build: /docker/poller
    command: python ./poller.py
    restart: always
  worker:
    build: /docker/worker
    command: python ./worker.py
    restart: always
  sender:
    build: /docker/sender
    command: python ./sender.py
    restart: always
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672