version: '3.1'

services:
  poller:
    build: poller
    command: python ./poller.py
    restart: always
    network_mode: host
    ports:
      - 15672:15672
      - 5672:5672
    depends_on:
      - rabbitmq
  worker:
    build: worker
    command: python ./worker.py
    restart: always
    network_mode: host
    ports:
      - 15672:15672
      - 5672:5672
    depends_on:
      - poller
  sender:
    build: sender
    command: python ./sender.py
    restart: always
    network_mode: host
    ports:
      - 15672:15672
      - 5672:5672
    depends_on:
      - worker
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    network_mode: host
    ports:
      - 15672:15672
      - 5672:5672