"""Add admin table

Revision ID: 161478a34ff0
Revises: b3970d78e6cc
Create Date: 2023-03-29 23:40:59.638995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161478a34ff0'
down_revision = 'b3970d78e6cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
