"""Add admin table

Revision ID: 1b10f37b3615
Revises: 161478a34ff0
Create Date: 2023-03-29 23:45:05.172919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b10f37b3615'
down_revision = '161478a34ff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
