"""Add admin table

Revision ID: 8a271946db3b
Revises: f1791b198989
Create Date: 2023-03-30 00:31:18.339852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a271946db3b'
down_revision = 'f1791b198989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('salt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey'),
    sa.UniqueConstraint('email', name='admins_email_key'),
    sa.UniqueConstraint('vk_id', name='admins_vk_id_key')
    )
    # ### end Alembic commands ###
