"""Add admin table

Revision ID: f1791b198989
Revises: 1b10f37b3615
Create Date: 2023-03-29 23:48:05.424589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1791b198989'
down_revision = '1b10f37b3615'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
