# Generated by Django 4.1.7 on 2023-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(unique=True),
        ),
    ]
