# Generated by Django 4.1.7 on 2023-03-31 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={
                "ordering": ["vk_id"],
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["created_at", "chat_id"],
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
            },
        ),
        migrations.AlterModelOptions(
            name="leader",
            options={
                "ordering": ["name", "last_name"],
                "verbose_name": "Лидер",
                "verbose_name_plural": "Лидеры",
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["name", "last_name"],
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
            },
        ),
        migrations.AlterModelOptions(
            name="round",
            options={
                "ordering": ["state"],
                "verbose_name": "Раунд",
                "verbose_name_plural": "Раунды",
            },
        ),
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.TextField(verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="leader",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="Администратор ли"
            ),
        ),
        migrations.AlterField(
            model_name="leader",
            name="last_name",
            field=models.TextField(verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="leader",
            name="name",
            field=models.TextField(verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="leader",
            name="total_score",
            field=models.IntegerField(
                default=0, verbose_name="Общее количество очков"
            ),
        ),
        migrations.AlterField(
            model_name="leader",
            name="total_wins",
            field=models.IntegerField(
                default=0, verbose_name="Общее количество побед"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="Администратор ли"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="is_plaid",
            field=models.BooleanField(default=False, verbose_name="Сыграл ли"),
        ),
        migrations.AlterField(
            model_name="player",
            name="is_voited",
            field=models.BooleanField(
                default=False, verbose_name="Проголосовал ли"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.TextField(verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.TextField(verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="player",
            name="score",
            field=models.IntegerField(
                default=0, verbose_name="Количество очков"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="state",
            field=models.IntegerField(default=0, verbose_name="Состояние"),
        ),
        migrations.AlterField(
            model_name="round",
            name="state",
            field=models.IntegerField(default=0, verbose_name="Состояние"),
        ),
    ]
