# Generated by Django 4.1.7 on 2023-03-31 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "games",
            "0003_remove_user_salt_remove_user_vk_id_alter_user_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("password", models.TextField()),
                ("salt", models.TextField()),
                ("vk_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField()),
                ("is_start", models.BooleanField(default=False)),
                ("is_end", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 3, 31, 0, 18, 46, 785701
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
                "db_table": "games",
            },
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vk_id", models.IntegerField()),
                ("is_admin", models.BooleanField(default=False)),
                ("name", models.TextField()),
                ("last_name", models.TextField()),
                ("photo_id", models.TextField()),
                ("total_score", models.IntegerField(default=0)),
                ("total_wins", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Лидер",
                "verbose_name_plural": "Лидеры",
                "db_table": "leaders",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.IntegerField(default=0)),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роунд",
                "verbose_name_plural": "Роунды",
                "db_table": "rounds",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("vk_id", models.IntegerField()),
                ("is_admin", models.BooleanField(default=False)),
                ("name", models.TextField()),
                ("last_name", models.TextField()),
                ("photo_id", models.TextField()),
                ("score", models.IntegerField(default=0)),
                ("state", models.IntegerField(default=0)),
                ("is_plaid", models.BooleanField(default=False)),
                ("is_voited", models.BooleanField(default=False)),
                (
                    "round_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="games.round",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
                "db_table": "players",
            },
        ),
    ]
