# Generated by Django 4.1.7 on 2023-03-31 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_admin_game_leader_round_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 31, 0, 19, 55, 646276, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
