# Generated by Django 4.1.7 on 2023-03-31 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
